name: Murtle Tests

on: [push, pull_request]

jobs:
  busted:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: [ "5.4", "5.3", "5.2", "5.1", "luajit" ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Lua/LuaJIT
      uses: leafo/gh-actions-lua@v10.0.0
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - name: Setup ‘luarocks’
      uses: leafo/gh-actions-luarocks@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libev-dev
        luarocks install busted
        luarocks install luacov
        luarocks install luacov-coveralls

    - name: Run tests
      run: busted --coverage --lpath="" --cpath="" --output=gtest -Xoutput --color .

    - name: Report test coverage
      if: ${{ success() }}
      continue-on-error: true
      run: luacov-coveralls -i src -e .luarocks
      env:
        COVERALLS_REPO_TOKEN: ${{ github.token }}
