name: Murtle Tests

on: [push, pull_request]

jobs:
  busted:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: [ "5.3", "5.2", "5.1", "luajit" ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Lua/LuaJIT
      uses: leafo/gh-actions-lua@v10.0.0
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - name: Setup ‘luarocks’
      uses: leafo/gh-actions-luarocks@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libev-dev
        luarocks install busted
        luarocks install luacov
        luarocks install luacov-cobertura

    - name: Run tests
      run: busted --coverage --output=junit -Xoutput test_results.xml .

    - name: Generate Test Coverage Report
      run: luacov-cobertura

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          test_results.xml

    # - name: Code Coverage Report
    #   uses: irongut/CodeCoverageSummary@v1.3.0
    #   with:
    #     filename: luacov.report.out
    #     badge: true
    #     fail_below_min: true
    #     format: markdown
    #     hide_branch_rate: false
    #     hide_complexity: true
    #     indicators: true
    #     output: both

    # - name: Add Coverage PR Comment
    #   uses: marocchino/sticky-pull-request-comment@v2
    #   if: github.event_name == 'pull_request'
    #   with:
    #     recreate: true
    #     path: code-coverage-results.md
