name: Murtle Tests

on: [push, pull_request]

jobs:
  busted:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: [ "5.3", "5.2", "5.1", "luajit" ]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Lua/LuaJIT
      uses: leafo/gh-actions-lua@v10.0.0
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - name: Setup ‘luarocks’
      uses: leafo/gh-actions-luarocks@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libev-dev lcov
        luarocks install busted
        luarocks install luacov
        luarocks install luacov-cobertura
        luarocks install luacov-reporter-lcov

    - name: Run tests
      run: busted --coverage --output=junit -Xoutput test_results.xml .

    - name: Generate Test Coverage Report
      run: luacov -r lcov

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          test_results.xml

    - name: Report code coverage
      uses: zgosalvez/github-actions-report-lcov@v3
      with:
        coverage-files: luacov.report.out
        minimum-coverage: 80
        artifact-name: code-coverage-report
        github-token: ${{ secrets.GITHUB_TOKEN }}
        update-comment: true
